public enum SysMLKind {
    NAMESPACE,
    PACKAGE,
    FEATURE,
    ELEMENT,
    IMPORT,
    ATTRIBUTE_DEFINITION, PART_DEFINITION, PART_USAGE, ATTRIBUTE_USAGE, ITEM_USAGE_OUT, ITEM_USAGE_IN, CLASS, ITEM_USAGE_INOUT, ITEM_USAGE, PORT_USAGE, PORT_DEFINITION, ITEM_DEFINITION;
}
